/* 
 *  Create & init site content
 */

-- ITEMS --

CREATE TABLE IF NOT EXISTS rect_pos (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  min_x INTEGER DEFAULT 0,
  max_x INTEGER DEFAULT 0,
  min_y INTEGER DEFAULT 0,
  max_y INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS rect_temps (
  id INTEGER PRIMARY KEY AUTO_INCREMENT,
  DateCreated DATETIME
);
